### ISSUE TITLE
Use with MLDataPattern + Flux (FluxTraining.jl maybe)?

### ISSUE THREAD

**Issue by drozzy** [lorenzoh/DLPipelines.jl#12]
I mean this looks interesting, conceptually.
I would be curious to see how it actually translates into a complete example.
I admit that the https://github.com/lorenzoh/DLPipelines.jl/blob/master/docs/methods/imageclassification.jl example is a bit too advanced.
Some things that are not clear are:
- Where did ImageClassification come from? It would be nice to explain how it was created
- What is meant by `Context` on line 48?
- What is `Training()`?
- The `{cell=main}` comments are distracting a bit
- Would be nice to see training (using https://github.com/lorenzoh/FluxTraining.jl for example)

**Comment by lorenzoh** [comment]
I'm currently writing a tutorial on all that which includes a follow-along of a simpler implementation of `ImageClassification`.

The `cell` comments are for Publish.jl to generate the docs. Due to some changes I made in DataAugmentation.jl the example is broken currently, though 😅

**Comment by lorenzoh** [comment]
You can read a draft version of the article here: https://www.notion.so/holylorenzo/Deep-learning-workflow-Ecosystem-overview-c5648bd1951b404d911fe705eced0e41

**Comment by drozzy** [comment]
Thanks. But no description of the creation of the task yet right? Unless I missed it somewhere.

**Comment by lorenzoh** [comment]
It's there, the definition of `ImageClassification`
