### ISSUE TITLE
usage of DLPipelines.predict

### ISSUE THREAD

**Issue by AbhimanyuAryan** [lorenzoh/DLPipelines.jl#18]
hey @lorenzoh I don't understand what should go as `method`

```julia
DLPipelines.predict(load(FILE_PATH), "imgnet.jld2")
```

The source code doesn't have types as argument list which makes it little confusing

```repl-julia
HTTP.request("GET", "http://127.0.0.1:8000/predict").body |> String
┌ Error: 2021-12-27 03:02:26 Exception while generating log record in module DetectBears at /Users/abhi/Git/stipple-fastai/DetectBears/routes.jl:55
│   exception =
│    MethodError: no method matching predict(::Matrix{ColorTypes.RGB{FixedPointNumbers.N0f8}}, ::String)
│    Closest candidates are:
│      predict(::Any, ::Any, ::Any; device, undevice, context) at /Users/abhi/.julia/packages/DLPipelines/HoDSq/src/inference.jl:8
```

**Comment by lorenzoh** [comment]
`method` is a learning method. It's what you get from constructors like `ImageClassificationSingle` or what you build using `BlockMethod`/`SupervisedMethod`. See the [serialization tutorial](https://fluxml.ai/FastAI.jl/dev/notebooks/serialization.ipynb.html) for usage of `predictbatch`; `predict` is then the same but only taking in a single image, not a vector of images.

**Comment by AbhimanyuAryan** [comment]
thanks @lorenzoh
